# Generated by Django 3.1.2 on 2021-03-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(through='app.PhotoTags', to='app.Tag'),
        ),
    ]
